[metadata]
name = "flexoki-darkfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#CECDC3"
background = "#100F0F"
cursor_bg = "#CECDC3"
cursor_border = "#CECDC3"
cursor_fg = "#100F0F"
compose_cursor = '#bc5215'
selection_bg = "#282726"
selection_fg = "#CECDC3"
scrollbar_thumb = "#878580"
split = "#000000"
visual_bell = "#CECDC3"
ansi = ["#343331", "#af3029", "#66800b", "#ad8301", "#205ea6", "#5e409d", "#24837b", "#cecdc3"]
brights = ["#575653", "#d14d41", "#879a39", "#d0a215", "#4385be", "#8b7ec8", "#3aa99f", "#f2f0e5"]

[colors.indexed]
16 = "#a02f6f"
17 = "#bc5215"

[colors.tab_bar]
background = "#000000"
inactive_tab_edge = "#000000"
inactive_tab_edge_hover = "#1C1B1A"

[colors.tab_bar.active_tab]
bg_color = "#878580"
fg_color = "#100F0F"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1C1B1A"
fg_color = "#B7B5AC"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#282726"
fg_color = "#CECDC3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#100F0F"
fg_color = "#B7B5AC"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#282726"
fg_color = "#CECDC3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

