# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

[colors.primary]
background = "#171414"
foreground = "#cac5c4"
dim_foreground = "#8d8989"
bright_foreground = "#d9d4d3"

[colors.cursor]
text = "#cac5c4"
cursor = "#8d8989"

[colors.vi_mode_cursor]
text = "#cac5c4"
cursor = "#009d9a"

[colors.search.matches]
foreground = "#cac5c4"
background = "#393939"

[colors.search.focused_match]
foreground = "#cac5c4"
background = "#eb6200"

[colors.footer_bar]
foreground = "#cac5c4"
background = "#362f2f"

[colors.hints.start]
foreground = "#cac5c4"
background = "#eb6200"

[colors.hints.end]
foreground = "#cac5c4"
background = "#362f2f"

[colors.selection]
text = "#cac5c4"
background = "#262626"

[colors.normal]
black = "#3c3838"
red = "#da1e28"
green = "#24a148"
yellow = "#b28600"
blue = "#4589ff"
magenta = "#a56eff"
cyan = "#009d9a"
white = "#cac5c4"

[colors.bright]
black = "#565151"
red = "#fa4d56"
green = "#6fdc8c"
yellow = "#f1c21b"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#08bdba"
white = "#f7f3f2"

[colors.dim]
black = "#272525"
red = "#a2191f"
green = "#0e6027"
yellow = "#684e00"
blue = "#0043ce"
magenta = "#6929c4"
cyan = "#005d5d"
white = "#8f8b8b"

[[colors.indexed_colors]]
index = 16
color = "#eb6200"

[[colors.indexed_colors]]
index = 17
color = "#ee5396"
