[metadata]
name = "carbonfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#cac5c4"
background = "#171414"
cursor_bg = "#cac5c4"
cursor_border = "#cac5c4"
cursor_fg = "#171414"
compose_cursor = '#eb6200'
selection_bg = "#262626"
selection_fg = "#cac5c4"
scrollbar_thumb = "#504e4d"
split = "#0d0b0b"
visual_bell = "#cac5c4"
ansi = ["#3c3838", "#da1e28", "#24a148", "#b28600", "#4589ff", "#a56eff", "#009d9a", "#cac5c4"]
brights = ["#565151", "#fa4d56", "#6fdc8c", "#f1c21b", "#78a9ff", "#be95ff", "#08bdba", "#f7f3f2"]

[colors.indexed]
16 = "#ee5396"
17 = "#eb6200"

[colors.tab_bar]
background = "#0d0b0b"
inactive_tab_edge = "#0d0b0b"
inactive_tab_edge_hover = "#262121"

[colors.tab_bar.active_tab]
bg_color = "#504e4d"
fg_color = "#171414"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#262121"
fg_color = "#8d8989"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#362f2f"
fg_color = "#cac5c4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#171414"
fg_color = "#8d8989"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#362f2f"
fg_color = "#cac5c4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

